export type Scheme = {
  id: string;
  name: string;
  level: 'Central' | 'State';
  ministry: string;
  description: string;
  benefits: string;
  eligibility: string;
  category: 'Housing' | 'Health' | 'Employment' | 'Education' | 'Agriculture' | 'Social Security' | 'Food' | 'Financial';
};

export const GOVERNMENT_SCHEMES: Scheme[] = [
  // ── Central Schemes ──────────────────────────────────────
  {
    id: 'pmay',
    name: 'PM Awas Yojana (PMAY)',
    level: 'Central',
    ministry: 'Ministry of Housing & Urban Affairs',
    description: 'Affordable housing for all by 2024',
    benefits: 'Financial assistance up to ₹2.67 lakh for house construction',
    eligibility: 'BPL families, EWS, LIG without pucca house',
    category: 'Housing',
  },
  {
    id: 'pmjay',
    name: 'Ayushman Bharat (PMJAY)',
    level: 'Central',
    ministry: 'Ministry of Health & Family Welfare',
    description: 'Health insurance coverage up to ₹5 lakh per family per year',
    benefits: '₹5 lakh health insurance, free secondary & tertiary care',
    eligibility: 'BPL families as per SECC 2011 database',
    category: 'Health',
  },
  {
    id: 'mgnregs',
    name: 'MGNREGS (Job Card)',
    level: 'Central',
    ministry: 'Ministry of Rural Development',
    description: '100 days of guaranteed wage employment per year',
    benefits: '100 days/year guaranteed employment, ₹220+ daily wage',
    eligibility: 'Any rural adult household willing to do unskilled manual work',
    category: 'Employment',
  },
  {
    id: 'pmkisan',
    name: 'PM Kisan Samman Nidhi',
    level: 'Central',
    ministry: 'Ministry of Agriculture',
    description: '₹6000/year direct income support to farmer families',
    benefits: '₹6,000/year in 3 installments of ₹2,000',
    eligibility: 'Small & marginal farmers with less than 2 hectares of land',
    category: 'Agriculture',
  },
  {
    id: 'pmmvy',
    name: 'PM Matru Vandana Yojana',
    level: 'Central',
    ministry: 'Ministry of Women & Child Development',
    description: 'Maternity benefit for first live birth',
    benefits: '₹6,000 maternity benefit in 3 installments',
    eligibility: 'Pregnant & lactating mothers for first live birth (19+ years)',
    category: 'Social Security',
  },
  {
    id: 'pmjjby',
    name: 'PM Jeevan Jyoti Bima Yojana',
    level: 'Central',
    ministry: 'Ministry of Finance',
    description: 'Life insurance scheme',
    benefits: '₹2 lakh life cover at ₹436/year premium',
    eligibility: 'Age 18–50, savings bank account holder',
    category: 'Financial',
  },
  {
    id: 'pmsby',
    name: 'PM Suraksha Bima Yojana',
    level: 'Central',
    ministry: 'Ministry of Finance',
    description: 'Accidental insurance scheme',
    benefits: '₹2 lakh accidental death/disability cover at ₹20/year',
    eligibility: 'Age 18–70, savings bank account holder',
    category: 'Financial',
  },
  {
    id: 'pds',
    name: 'Ration Card (PDS)',
    level: 'State',
    ministry: 'Civil Supplies Department',
    description: 'Subsidised food grains through Public Distribution System',
    benefits: 'Rice/wheat at ₹1-3/kg, essential commodities at subsidised rates',
    eligibility: 'BPL/AAY families registered in state ration database',
    category: 'Food',
  },
  // ── State Schemes (AP/Telangana) ─────────────────────────
  {
    id: 'ysrbc',
    name: 'YSR BC Nestham',
    level: 'State',
    ministry: 'AP BC Welfare Dept',
    description: '₹10,000/year to BC women for self-employment',
    benefits: '₹10,000/year direct benefit transfer',
    eligibility: 'BC category women aged 45–60 years',
    category: 'Financial',
  },
  {
    id: 'ysrpension',
    name: 'YSR Pension Kanuka',
    level: 'State',
    ministry: 'AP Social Welfare Dept',
    description: 'Monthly pension to elderly, widows, disabled',
    benefits: '₹2,750–₹3,000/month pension',
    eligibility: 'Old age (60+), widows, disabled, single women, toddy tappers',
    category: 'Social Security',
  },
  {
    id: 'ysrammavodi',
    name: 'Jagananna Amma Vodi',
    level: 'State',
    ministry: 'AP School Education Dept',
    description: '₹15,000/year to mothers of school-going children',
    benefits: '₹15,000/year for each school-going child',
    eligibility: 'BPL mothers with children enrolled in government schools',
    category: 'Education',
  },
  {
    id: 'ysrcheyutha',
    name: 'YSR Cheyutha',
    level: 'State',
    ministry: 'AP BC, EBC, Kapu Welfare Dept',
    description: '₹18,750/year for BC/EBC/Kapu/Minority women',
    benefits: '₹18,750/year for 4 years (total ₹75,000)',
    eligibility: 'BC/EBC/Kapu/Minority women aged 45–60 below poverty line',
    category: 'Financial',
  },
  {
    id: 'ysrrythu',
    name: 'YSR Rythu Bharosa',
    level: 'State',
    ministry: 'AP Agriculture Dept',
    description: '₹13,500/year to farmer families',
    benefits: '₹13,500/year (₹7,500 state + ₹6,000 PM Kisan)',
    eligibility: 'AP farmers with agricultural land in state records',
    category: 'Agriculture',
  },
  {
    id: 'ysrcaps',
    name: 'YSR CAPS (Crop Insurance)',
    level: 'State',
    ministry: 'AP Agriculture Dept',
    description: 'Crop insurance premium paid by government',
    benefits: 'Full crop insurance premium reimbursed by state govt',
    eligibility: 'AP farmers with Pattadar Passbooks/land records',
    category: 'Agriculture',
  },
  {
    id: 'jaganannavidyadeevena',
    name: 'Jagananna Vidya Deevena',
    level: 'State',
    ministry: 'AP Higher Education Dept',
    description: 'Full fee reimbursement for higher education',
    benefits: 'Full tuition fee reimbursement for college students',
    eligibility: 'SC/ST/BC/EBC/Kapu/Minority students in govt/aided institutions',
    category: 'Education',
  },
  {
    id: 'pmujjwala',
    name: 'PM Ujjwala Yojana',
    level: 'Central',
    ministry: 'Ministry of Petroleum & Natural Gas',
    description: 'Free LPG connections to BPL women',
    benefits: 'Free LPG connection + first refill + hotplate',
    eligibility: 'Women from BPL households without existing LPG connection',
    category: 'Social Security',
  },
  {
    id: 'pmsvvanidhi',
    name: 'PM SVANidhi (Street Vendor Loan)',
    level: 'Central',
    ministry: 'Ministry of Housing & Urban Affairs',
    description: 'Micro-credit for street vendors',
    benefits: '₹10,000 collateral-free loan, extendable to ₹50,000',
    eligibility: 'Urban street vendors with vending certificate',
    category: 'Financial',
  },
  {
    id: 'mudra',
    name: 'PM MUDRA Yojana',
    level: 'Central',
    ministry: 'Ministry of Finance',
    description: 'Loans up to ₹10 lakh for small businesses',
    benefits: 'Shishu (₹50K), Kishore (₹5L), Tarun (₹10L) loans',
    eligibility: 'Non-farm income-generating small/micro enterprises',
    category: 'Financial',
  },
];

export const SCHEME_CATEGORIES = [
  'Housing', 'Health', 'Employment', 'Education',
  'Agriculture', 'Social Security', 'Food', 'Financial'
] as const;
